language: python
python:
        - "3.5.2"
install:
        - pip install -r ./requirements.txt
        - pip install python-coveralls
script:

        - python3 ./manage.py test api
        - coverage run --source=python3 manage.py test api
        - coverage erase
        - cd api/
        - coverage combine
        - coverage report -m
        - cp .coverage ../
        - cd ..
        - coverage report -m
after_success:
        - coveralls
