language: python
python:
        - "3.5.2"
install:
        - pip install -r ./requirements.txt
        - pip install coveralls
script:
        - python3 ./manage.py test api
        - coverage run --source=./ manage.py test
after_success:
        - coveralls
