language: python
python:
        - "3.5.2"
install:
        - pip install -r ./requirements.txt
        - pip install coveralls
script:

        - python3 ./manage.py test api --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
after_success:
        - coveralls
