# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-18 18:00
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('place', '0001_initial'),
    ]

    operations = [

        migrations.CreateModel(
            name='Trip',
            fields=[
                ('userId', models.CharField(max_length=200,primary_key=True)),
                ('tripName', models.CharField(max_length=200, default="None")),
                ('tripDescription', models.CharField(max_length=500, default="None")),
            ],
        ),
         migrations.AddField(
            model_name='trip',
            name='places',
            field=models.ManyToManyField(to='place.Place'),
        ),

        migrations.AddField(
            model_name='trip',
            name='guides',
            field=models.ManyToManyField(to='user.User'),
        ),
    ]
