# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-18 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200, default = "None")),
                ('mail', models.CharField(max_length=200, default = "None")),
                ('imageUrl', models.CharField(max_length=500, default = "None")),
                ('is_guide', models.BooleanField(default=False)),
                ('gradesNumber', models.IntegerField(default = 0)),
                ('gradesSum', models.IntegerField(default = 0))
            ],
        ),
    ]
